FROM busybox:1.24.1
MAINTAINER kpacha

ENV FORMAT=json
ENV CONFIG_PATH=/
ENV CONFIG_FILE=conf

COPY ./mesos-influxdb-collector /mesos-influxdb-collector
COPY ./conf.json /conf.json

ENTRYPOINT ["/./mesos-influxdb-collector"]
